export { default as LandingPage } from 'pages/LandingPage'
export { default as LoginPage } from 'pages/LoginPage'
export { default as RegisterPage } from 'pages/RegisterPage'
export { default as PostDetailPage } from 'pages/PostDetailPage'
export { default as UserDetailPage } from 'pages/UserDetailPage'